<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-10-22T23:06:32+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'piXlogic',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1474747970,
        'do_page_reindex_check' => false,
    ),
    'cache' => array(
        'blocks' => false,
        'assets' => false,
        'theme_css' => false,
        'overrides' => true,
        'pages' => '0',
        'full_page_lifetime' => 'default',
        'full_page_lifetime_value' => null,
    ),
    'theme' => array(
        'compress_preprocessor_output' => false,
        'generate_less_sourcemap' => false,
    ),
    'debug' => array(
        'detail' => 'debug',
        'display_errors' => true,
    ),
);
