<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2016-09-24T20:12:50+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.access_entity_updated
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return array(
    'site' => 'PixLogic',
    'version_installed' => '5.7.5.9',
    'misc' => array(
        'access_entity_updated' => 1474747970,
    ),
);
